package com.example.mapper.mappers;

import com.example.mapper.entity.DispatchFilterConfig;
import com.example.mapper.entity.DispatchFilterConfigExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface DispatchFilterConfigMapper {
    long countByExample(DispatchFilterConfigExample example);

    int deleteByExample(DispatchFilterConfigExample example);

    int insert(DispatchFilterConfig record);

    int insertSelective(DispatchFilterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_filter_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DispatchFilterConfig> selectByExampleSelective(@Param("example") DispatchFilterConfigExample example, @Param("selective") DispatchFilterConfig.Column ... selective);

    List<DispatchFilterConfig> selectByExample(DispatchFilterConfigExample example);

    int updateByExampleSelective(@Param("record") DispatchFilterConfig record, @Param("example") DispatchFilterConfigExample example);

    int updateByExample(@Param("record") DispatchFilterConfig record, @Param("example") DispatchFilterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_filter_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DispatchFilterConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_filter_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DispatchFilterConfig> list, @Param("selective") DispatchFilterConfig.Column ... selective);
}